-- VaultDrop: Secure Secret Delivery Agent

-- Database schema migration

-- This sets up the zero-knowledge secret delivery system

-- Enable UUID generation

create extension if not exists "pgcrypto";

-- ============================================

-- DELIVERIES TABLE

-- Stores encrypted secret deliveries with access control

-- The server NEVER sees plaintext — only encrypted data + PIN hash

-- ============================================

-- id and creator_token are compact 22-char URL-safe IDs generated by the app

create table deliveries (

  id text primary key,

-- Encrypted content (client-side AES-256-GCM) — nullable so revoke can wipe it

  encrypted_data text,               -- base64 AES-256-GCM ciphertext (null after revoke)

  nonce text,                         -- base64 AES-GCM nonce (96-bit)

  salt text,                          -- base64 PBKDF2 salt (128-bit)

  iterations integer not null default 600000,  -- PBKDF2 iterations

  -- PIN verification (bcrypt hash — server can validate without seeing PIN)

  pin_hash text,

  -- Access policy

  max_views integer default 1,            -- 0 = unlimited, 1 = one-time (default)

  expires_at timestamptz,                 -- NULL = no expiry

  burn_after_reading boolean default true, -- destroy after first access

  -- Creator control (token for authorization)

  creator_token text,

  -- Status lifecycle: active → accessed/destroyed → expired/revoked/locked/destroyed

  status varchar(20) default 'active' check (status in ('active', 'accessed', 'expired', 'revoked', 'locked', 'destroyed')),

  view_count integer default 0,

  failed_attempts integer default 0,

  -- Metadata (not sensitive — just a label for the creator's reference)

  title text,

  content_type text default 'text/plain',

  -- Timestamps

  created_at timestamptz default now(),

  accessed_at timestamptz,

  destroyed_at timestamptz

);

-- ============================================

-- ACCESS EVENTS TABLE

-- Logs all delivery lifecycle events for creator audit

-- ============================================

create table access_events (

  id uuid primary key default gen_random_uuid(),

  delivery_id text references deliveries(id) on delete cascade,

  event_type varchar(50) not null,  -- created, pin_validated, pin_failed, accessed, expired, revoked, locked, destroyed

  event_time timestamptz default now(),

  metadata jsonb                     -- additional event details (IP, remaining attempts, etc.)

);

-- ============================================

-- INDEXES

-- ============================================

-- Find expired deliveries for auto-purge

create index idx_deliveries_expires_at on deliveries(expires_at)

  where expires_at is not null and status = 'active';

-- Lookup by status

create index idx_deliveries_status on deliveries(status);

-- Lookup by creator token

create index idx_deliveries_creator_token on deliveries(creator_token);

-- Lookup events by delivery

create index idx_access_events_delivery_id on access_events(delivery_id);

-- Order events chronologically

create index idx_access_events_event_time on access_events(event_time);

-- ============================================

-- ROW LEVEL SECURITY

-- ============================================

alter table deliveries enable row level security;

alter table access_events enable row level security;

-- The API (using service_role key) has full access — RLS is bypassed

-- for the service_role, so no policies are needed for API access.

-- Anonymous access is handled in API route logic.

-- (Policies below are optional — they prevent direct table access

-- without the service_role key, but our routes always use service_role)

-- If using anon key directly (not recommended), restrict reads:

-- create policy "Anonymous can read active delivery metadata only"

--   on deliveries for select

--   using (status = 'active');

-- (Note: we don't expose encrypted data via anon RLS — it goes through the API which

--  validates PIN first)